"""TaskForge — CLI interface. Auto-generated by HyperFlow Autonomous Pipeline."""

import argparse
import json
import sys
from db import init_db, create_task, list_tasks, update_task, complete_task, delete_task, get_receipts


def cmd_add(args):
    tid = create_task(args.title, args.description, args.priority)
    print(f"Created task #{tid}: {args.title}")


def cmd_list(args):
    tasks = list_tasks(args.status)
    if not tasks:
        print("No tasks found.")
        return
    print(f"{'ID':>4}  {'ST':>4}  {'PR':>2}  Title")
    print("-" * 50)
    for t in tasks:
        st = "DONE" if t["status"] == "done" else "OPEN"
        print(f"{t['id']:>4}  {st:>4}  {t['priority']:>2}  {t['title']}")


def cmd_done(args):
    if complete_task(args.id):
        print(f"Completed task #{args.id}")
    else:
        print(f"Task #{args.id} not found")


def cmd_delete(args):
    delete_task(args.id)
    print(f"Deleted task #{args.id}")


def cmd_receipts(args):
    recs = get_receipts(args.limit)
    if not recs:
        print("No receipts found.")
        return
    for r in recs:
        print(f"  [{r['id']}] {r['action']:>6} {r['entity_type']}#{r['entity_id']} — {r['timestamp']}")


def cmd_status(args):
    tasks = list_tasks()
    open_count = sum(1 for t in tasks if t["status"] == "open")
    done_count = sum(1 for t in tasks if t["status"] == "done")
    recs = get_receipts(100)
    print(f"TaskForge Status")
    print(f"  Open tasks:   {open_count}")
    print(f"  Done tasks:   {done_count}")
    print(f"  Total tasks:  {len(tasks)}")
    print(f"  Receipts:     {len(recs)}")


def main():
    parser = argparse.ArgumentParser(prog="taskforge", description="TaskForge — CLI task manager with receipts")
    sub = parser.add_subparsers(dest="command")

    p_add = sub.add_parser("add", help="Add a task")
    p_add.add_argument("title", help="Task title")
    p_add.add_argument("-d", "--description", default="", help="Task description")
    p_add.add_argument("-p", "--priority", type=int, default=0, help="Priority (0-5)")
    p_add.set_defaults(func=cmd_add)

    p_list = sub.add_parser("list", help="List tasks")
    p_list.add_argument("-s", "--status", choices=["open", "done"], help="Filter by status")
    p_list.set_defaults(func=cmd_list)

    p_done = sub.add_parser("done", help="Mark task as done")
    p_done.add_argument("id", type=int, help="Task ID")
    p_done.set_defaults(func=cmd_done)

    p_del = sub.add_parser("delete", help="Delete a task")
    p_del.add_argument("id", type=int, help="Task ID")
    p_del.set_defaults(func=cmd_delete)

    p_rec = sub.add_parser("receipts", help="Show recent receipts")
    p_rec.add_argument("-n", "--limit", type=int, default=20, help="Number of receipts")
    p_rec.set_defaults(func=cmd_receipts)

    p_status = sub.add_parser("status", help="Show TaskForge status")
    p_status.set_defaults(func=cmd_status)

    args = parser.parse_args()
    if not args.command:
        parser.print_help()
        sys.exit(1)

    init_db()
    args.func(args)


if __name__ == "__main__":
    main()
