"""TaskForge — SQLite database layer. Auto-generated by HyperFlow Autonomous Pipeline."""

import sqlite3
from datetime import datetime
from pathlib import Path

DB_PATH = Path(__file__).parent / "taskforge.db"


def get_db():
    conn = sqlite3.connect(str(DB_PATH))
    conn.row_factory = sqlite3.Row
    return conn


def init_db():
    conn = get_db()
    conn.executescript("""
        CREATE TABLE IF NOT EXISTS tasks (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            title TEXT NOT NULL,
            description TEXT DEFAULT '',
            status TEXT DEFAULT 'open',
            priority INTEGER DEFAULT 0,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        );
        CREATE TABLE IF NOT EXISTS receipts (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            action TEXT NOT NULL,
            entity_type TEXT DEFAULT 'task',
            entity_id INTEGER,
            details TEXT DEFAULT '{}',
            timestamp TEXT NOT NULL
        );
    """)
    conn.commit()
    conn.close()


def create_task(title, description="", priority=0):
    conn = get_db()
    now = datetime.utcnow().isoformat() + "Z"
    cur = conn.execute(
        "INSERT INTO tasks (title, description, priority, created_at, updated_at) VALUES (?, ?, ?, ?, ?)",
        (title, description, priority, now, now)
    )
    task_id = cur.lastrowid
    conn.execute(
        "INSERT INTO receipts (action, entity_type, entity_id, details, timestamp) VALUES (?, ?, ?, ?, ?)",
        ("create", "task", task_id, f'{{"title": "{title}"}}', now)
    )
    conn.commit()
    conn.close()
    return task_id


def list_tasks(status=None):
    conn = get_db()
    if status:
        rows = conn.execute("SELECT * FROM tasks WHERE status = ? ORDER BY priority DESC, id DESC", (status,)).fetchall()
    else:
        rows = conn.execute("SELECT * FROM tasks ORDER BY priority DESC, id DESC").fetchall()
    conn.close()
    return [dict(r) for r in rows]


def update_task(task_id, **fields):
    conn = get_db()
    now = datetime.utcnow().isoformat() + "Z"
    allowed = {"title", "description", "status", "priority"}
    updates = {k: v for k, v in fields.items() if k in allowed}
    if not updates:
        return False
    set_clause = ", ".join(f"{k} = ?" for k in updates)
    values = list(updates.values()) + [now, task_id]
    conn.execute(f"UPDATE tasks SET {set_clause}, updated_at = ? WHERE id = ?", values)
    conn.execute(
        "INSERT INTO receipts (action, entity_type, entity_id, details, timestamp) VALUES (?, ?, ?, ?, ?)",
        ("update", "task", task_id, str(updates), now)
    )
    conn.commit()
    conn.close()
    return True


def complete_task(task_id):
    return update_task(task_id, status="done")


def delete_task(task_id):
    conn = get_db()
    now = datetime.utcnow().isoformat() + "Z"
    conn.execute("DELETE FROM tasks WHERE id = ?", (task_id,))
    conn.execute(
        "INSERT INTO receipts (action, entity_type, entity_id, details, timestamp) VALUES (?, ?, ?, ?, ?)",
        ("delete", "task", task_id, "{}", now)
    )
    conn.commit()
    conn.close()


def get_receipts(limit=20):
    conn = get_db()
    rows = conn.execute(
        "SELECT * FROM receipts ORDER BY id DESC LIMIT ?", (limit,)
    ).fetchall()
    conn.close()
    return [dict(r) for r in rows]
