#!/usr/bin/env python3
"""
TaskForge — CLI task manager with SQLite storage and receipt logging.
Auto-generated by HyperFlow Autonomous Pipeline.
"""

import sys
from cli import main as cli_main

if __name__ == "__main__":
    cli_main()
