"""TaskForge — CLI tests. Auto-generated by HyperFlow Autonomous Pipeline."""

import os
import sys
import tempfile
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).parent))


@pytest.fixture(autouse=True)
def temp_db(monkeypatch):
    with tempfile.TemporaryDirectory() as td:
        db_path = Path(td) / "test_taskforge.db"
        monkeypatch.setattr("db.DB_PATH", db_path)
        from db import init_db
        init_db()
        yield db_path


def test_create_task():
    from db import create_task, list_tasks
    tid = create_task("Test task", "description", priority=2)
    assert tid > 0
    tasks = list_tasks()
    assert len(tasks) == 1
    assert tasks[0]["title"] == "Test task"
    assert tasks[0]["priority"] == 2


def test_complete_task():
    from db import create_task, complete_task, list_tasks
    tid = create_task("Complete me")
    assert complete_task(tid)
    tasks = list_tasks(status="done")
    assert len(tasks) == 1
    assert tasks[0]["status"] == "done"


def test_delete_task():
    from db import create_task, delete_task, list_tasks
    tid = create_task("Delete me")
    delete_task(tid)
    tasks = list_tasks()
    assert len(tasks) == 0


def test_receipts_logged():
    from db import create_task, get_receipts
    create_task("Receipt test")
    recs = get_receipts()
    assert len(recs) >= 1
    assert recs[0]["action"] == "create"


def test_list_filter():
    from db import create_task, complete_task, list_tasks
    t1 = create_task("Open task")
    t2 = create_task("Done task")
    complete_task(t2)
    open_tasks = list_tasks(status="open")
    done_tasks = list_tasks(status="done")
    assert len(open_tasks) == 1
    assert len(done_tasks) == 1
