//
//  ScreenPulse.swift
//  ScreenPulse
//
//  Auto-generated by Autopilot. Real-time screen activity monitor
//

import SwiftUI
import AppKit

@main
struct ScreenPulseApp: App {
    var body: some Scene {
        MenuBarExtra("ScreenPulse", systemImage: "textformat") {
            ContentView()
        }
        .menuBarExtraStyle(.window)
    }
}

struct ContentView: View {
    @State private var items: [String] = []
    @State private var input = ""

    var body: some View {
        VStack(spacing: 12) {
            Text("ScreenPulse")
                .font(.system(size: 14, weight: .bold, design: .monospaced))
                .foregroundColor(.orange)

            Text("Real-time screen activity monitor")
                .font(.system(size: 10, design: .monospaced))
                .foregroundColor(.gray)
                .multilineTextAlignment(.center)

            HStack {
                TextField("Add item...", text: $input)
                    .textFieldStyle(.roundedBorder)
                Button("Add") {
                    if !input.isEmpty {
                        items.append(input)
                        input = ""
                    }
                }
            }

            List(items, id: \.self) { item in
                Text(item)
                    .font(.system(size: 11, design: .monospaced))
            }
            .frame(minHeight: 200)

            Text("{items.count} items")
                .font(.system(size: 9, design: .monospaced))
                .foregroundColor(.gray)
        }
        .padding(16)
        .frame(width: 320, height: 400)
    }
}
