"""Adversarial Attribution Underwriting (AAU).

Decides whether a claimed value is finance-readable.

Locks the baseline by hash. Strips counterfactual value. Weights
evidence/reputation/settlement/exchangeability. Subtracts fraud
penalties. Emits a receipt with status:

    FINANCE_READABLE_OPEN   — claim survives, open for settlement
    REJECTED_GAMING         — gaming flags triggered, claim rejected
    SETTLED_FINANCE_READABLE — claim settled and verified
    REJECTED_NO_DELTA       — no real improvement over baseline
    REJECTED_NON_POOLABLE   — claim cannot be pooled/securitized

The AAU is the adversarial layer. It assumes every claim is guilty
until proven by evidence, receipts, and verifiable delta.
"""

import hashlib
import json
import uuid
from datetime import datetime
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple
from enum import Enum


class ClaimStatus(Enum):
    FINANCE_READABLE_OPEN = "FINANCE_READABLE_OPEN"
    REJECTED_GAMING = "REJECTED_GAMING"
    SETTLED_FINANCE_READABLE = "SETTLED_FINANCE_READABLE"
    REJECTED_NO_DELTA = "REJECTED_NO_DELTA"
    REJECTED_NON_POOLABLE = "REJECTED_NON_POOLABLE"
    PENDING = "PENDING"


@dataclass
class Baseline:
    """Locked baseline state for comparison."""
    label: str
    snapshot_hash: str
    timestamp: str
    metrics: Dict[str, float] = field(default_factory=dict)

    def lock_hash(self) -> str:
        """Compute deterministic hash of baseline state."""
        payload = json.dumps({
            'label': self.label,
            'snapshot_hash': self.snapshot_hash,
            'metrics': self.metrics,
        }, sort_keys=True).encode()
        return hashlib.sha256(payload).hexdigest()


@dataclass
class Evidence:
    """A single piece of evidence supporting a value claim."""
    evidence_id: str
    kind: str  # receipt, test_pass, endpoint_response, usage_log, file_hash
    source: str
    timestamp: str
    payload_hash: str
    weight: float = 1.0  # 0.0-1.0, how strong this evidence is
    verified: bool = False


@dataclass
class GamingFlags:
    """Flags that indicate gaming or fraud attempts."""
    counterfactual_inflation: bool = False  # claiming value that would have happened anyway
    phantom_revenue: bool = False           # revenue claimed without usage log
    self_dealing: bool = False              # usage by the creator only
    circular_reference: bool = False        # claim references itself as evidence
    unverifiable_delta: bool = False        # no measurable improvement over baseline
    duplicate_claim: bool = False           # same work claimed multiple times
    non_poolable: bool = False              # claim cannot be aggregated/securitized
    timing_manipulation: bool = False       # baseline set to make delta look bigger


@dataclass
class ValueClaim:
    """A claim of value generated by an executable artifact."""
    claim_id: str
    system_name: str
    baseline: Baseline
    evidence: List[Evidence] = field(default_factory=list)
    gaming_flags: GamingFlags = field(default_factory=GamingFlags)
    claimed_value_usd: float = 0.0
    counterfactual_value_usd: float = 0.0  # value that would have occurred anyway
    hours_avoided: float = 0.0
    confidence: float = 0.5
    exchangeability: float = 0.0  # 0-1, can this be sold/transferred?
    reputation: float = 0.5  # 0-1, track record of the claimant


class SettlementLedger:
    """Tracks settlement of value claims.

    A claim that settles becomes finance-readable.
    A claim that fails settlement is rejected with reason.
    """

    def __init__(self):
        self._settlements: List[Dict] = []
        self._chain_hash = None

    def settle(self, claim_id: str, status: ClaimStatus,
               settled_value: float = 0.0, reason: str = None) -> Dict:
        """Record a settlement decision."""
        entry = {
            'settlement_id': str(uuid.uuid4()),
            'claim_id': claim_id,
            'status': status.value,
            'settled_value_usd': round(settled_value, 2),
            'reason': reason or '',
            'timestamp': datetime.now().isoformat(),
            'previous_settlement': self._chain_hash,
        }
        # Chain hash
        payload = json.dumps({
            'settlement_id': entry['settlement_id'],
            'claim_id': claim_id,
            'status': entry['status'],
            'previous': self._chain_hash,
        }, sort_keys=True).encode()
        entry['chain_hash'] = hashlib.sha256(payload).hexdigest()
        self._chain_hash = entry['chain_hash']
        self._settlements.append(entry)
        return entry

    def verify_chain(self) -> Dict:
        """Verify the settlement chain is intact."""
        prev = None
        for s in self._settlements:
            expected_prev = prev
            if s['previous_settlement'] != expected_prev:
                return {'valid': False, 'broken_at': s['settlement_id']}
            prev = s['chain_hash']
        return {'valid': True, 'count': len(self._settlements)}

    def list_settlements(self) -> List[Dict]:
        return list(self._settlements)


class AdversarialAttributionUnderwriter:
    """Underwrites value claims through adversarial attribution.

    Process:
    1. Lock baseline by hash (deterministic, tamper-evident)
    2. Strip counterfactual value (what would have happened anyway)
    3. Check gaming flags (phantom revenue, self-dealing, circular refs)
    4. Weight evidence by kind, verification, and reputation
    5. Apply fraud penalties
    6. Emit receipt with finance-readable status

    The underwriter is adversarial: it assumes claims are guilty
    until proven by verifiable evidence.
    """

    # Evidence kind weights
    EVIDENCE_WEIGHTS = {
        'receipt': 0.9,
        'test_pass': 0.8,
        'endpoint_response': 0.7,
        'usage_log': 0.6,
        'file_hash': 0.4,
        'manual_attestation': 0.2,
    }

    # Gaming penalties (subtracted from score)
    GAMING_PENALTIES = {
        'counterfactual_inflation': 25,
        'phantom_revenue': 30,
        'self_dealing': 15,
        'circular_reference': 20,
        'unverifiable_delta': 25,
        'duplicate_claim': 15,
        'non_poolable': 10,
        'timing_manipulation': 20,
    }

    def __init__(self):
        self.ledger = SettlementLedger()

    def underwrite(self, claim: ValueClaim) -> Dict:
        """Underwrite a value claim through adversarial attribution.

        Returns the underwriting decision with status, score, and receipt.
        """
        # 1. Lock baseline
        baseline_hash = claim.baseline.lock_hash()

        # 2. Strip counterfactual value
        net_value = claim.claimed_value_usd - claim.counterfactual_value_usd
        if net_value <= 0 and claim.claimed_value_usd > 0:
            claim.gaming_flags.counterfactual_inflation = True

        # 3. Check gaming flags
        gaming_triggered = []
        for flag_name, penalty in self.GAMING_PENALTIES.items():
            if getattr(claim.gaming_flags, flag_name, False):
                gaming_triggered.append(flag_name)

        # 4. Weight evidence
        total_evidence_weight = 0.0
        verified_evidence = 0
        for ev in claim.evidence:
            kind_weight = self.EVIDENCE_WEIGHTS.get(ev.kind, 0.3)
            ev_weight = kind_weight * ev.weight * (1.0 if ev.verified else 0.5)
            total_evidence_weight += ev_weight
            if ev.verified:
                verified_evidence += 1

        # Normalize evidence score (0-100)
        evidence_score = min(100, total_evidence_weight * 20)

        # 5. Compute composite score
        reputation_score = claim.reputation * 100
        exchangeability_score = claim.exchangeability * 100
        confidence_score = claim.confidence * 100

        # Settlement history factor
        settlements = self.ledger.list_settlements()
        settled_count = sum(1 for s in settlements
                           if s['status'] == ClaimStatus.SETTLED_FINANCE_READABLE.value)
        settlement_score = min(100, settled_count * 20)

        composite = (
            evidence_score * 0.30 +
            reputation_score * 0.15 +
            settlement_score * 0.15 +
            exchangeability_score * 0.15 +
            confidence_score * 0.10 +
            (100 if net_value > 0 else 0) * 0.15
        )

        # 6. Apply gaming penalties
        total_penalty = sum(self.GAMING_PENALTIES[f] for f in gaming_triggered)
        final_score = max(0, composite - total_penalty)

        # 7. Determine status (check no-delta before gaming)
        if net_value <= 0:
            status = ClaimStatus.REJECTED_NO_DELTA
        elif gaming_triggered:
            # Severe gaming = reject
            severe = any(f in ('phantom_revenue', 'circular_reference',
                              'unverifiable_delta', 'timing_manipulation')
                        for f in gaming_triggered)
            if severe:
                status = ClaimStatus.REJECTED_GAMING
            elif 'non_poolable' in gaming_triggered:
                status = ClaimStatus.REJECTED_NON_POOLABLE
            else:
                status = ClaimStatus.REJECTED_GAMING
        elif net_value <= 0:
            status = ClaimStatus.REJECTED_NO_DELTA
        elif final_score >= 45:
            status = ClaimStatus.FINANCE_READABLE_OPEN
        else:
            status = ClaimStatus.PENDING

        # 8. Settle
        settled_value = 0.0
        if status == ClaimStatus.FINANCE_READABLE_OPEN:
            # Settle at a discount to claimed value
            discount = 1.0 - (final_score / 100.0) * 0.5  # max 50% of claim
            settled_value = net_value * discount
            status = ClaimStatus.SETTLED_FINANCE_READABLE

        settlement = self.ledger.settle(
            claim_id=claim.claim_id,
            status=status,
            settled_value=settled_value,
            reason='; '.join(gaming_triggered) if gaming_triggered else 'passed adversarial review',
        )

        # 9. Build receipt
        receipt = {
            'schema': 'membra.aau.underwriting_receipt.v1',
            'receipt_id': str(uuid.uuid4()),
            'timestamp': datetime.now().isoformat(),
            'claim_id': claim.claim_id,
            'system_name': claim.system_name,
            'baseline_hash': baseline_hash,
            'claimed_value_usd': round(claim.claimed_value_usd, 2),
            'counterfactual_value_usd': round(claim.counterfactual_value_usd, 2),
            'net_value_usd': round(net_value, 2),
            'evidence_count': len(claim.evidence),
            'verified_evidence': verified_evidence,
            'evidence_score': round(evidence_score, 1),
            'reputation_score': round(reputation_score, 1),
            'settlement_score': round(settlement_score, 1),
            'exchangeability_score': round(exchangeability_score, 1),
            'confidence_score': round(confidence_score, 1),
            'composite_score': round(composite, 1),
            'gaming_flags_triggered': gaming_triggered,
            'total_penalty': total_penalty,
            'final_score': round(final_score, 1),
            'status': status.value,
            'settled_value_usd': round(settled_value, 2),
            'settlement_id': settlement['settlement_id'],
            'chain_hash': settlement['chain_hash'],
        }

        return {
            'receipt': receipt,
            'status': status,
            'settled_value': settled_value,
            'gaming_flags': gaming_triggered,
            'score': final_score,
        }

    def verify_settlements(self) -> Dict:
        """Verify the settlement chain."""
        return self.ledger.verify_chain()
