#!/usr/bin/env python3
"""LinkOps — Auto-generated by HyperFlow Autonomous Loop."""

import argparse
import sys
from db import init_db, create_item, list_items, complete_item, get_receipts


def main():
    parser = argparse.ArgumentParser(prog="linkops", description="LinkOps")
    sub = parser.add_subparsers(dest="cmd")
    
    p_add = sub.add_parser("add", help="Add item")
    p_add.add_argument("title")
    
    p_list = sub.add_parser("list", help="List items")
    p_list.add_argument("-s", "--status", default=None)
    
    p_done = sub.add_parser("done", help="Complete item")
    p_done.add_argument("id", type=int)
    
    p_rec = sub.add_parser("receipts", help="Show receipts")
    
    args = parser.parse_args()
    if not args.cmd:
        parser.print_help()
        return
    
    init_db()
    
    if args.cmd == "add":
        tid = create_item(args.title)
        print(f"Created #{tid}: {args.title}")
    elif args.cmd == "list":
        items = list_items(args.status)
        for it in items:
            print(f"  #{it['id']:>3} [{it['status']:>6}] {it['title']}")
    elif args.cmd == "done":
        complete_item(args.id)
        print(f"Completed #{args.id}")
    elif args.cmd == "receipts":
        for r in get_receipts():
            print(f"  [{r['id']}] {r['action']} #{r['entity_id']} — {r['timestamp']}")


if __name__ == "__main__":
    main()
