"""VaultOps — SQLite layer. Auto-generated by HyperFlow Autonomous Loop."""

import json
import sqlite3
from datetime import datetime
from pathlib import Path

DB_PATH = Path(__file__).parent / "vaultops.db"


def get_db():
    conn = sqlite3.connect(str(DB_PATH))
    conn.row_factory = sqlite3.Row
    return conn


def init_db():
    conn = get_db()
    conn.executescript("""
        CREATE TABLE IF NOT EXISTS items (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            title TEXT NOT NULL,
            description TEXT DEFAULT '',
            status TEXT DEFAULT 'active',
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        );
        CREATE TABLE IF NOT EXISTS receipts (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            action TEXT NOT NULL,
            entity_id INTEGER,
            details TEXT DEFAULT '{}',
            timestamp TEXT NOT NULL
        );
    """)
    conn.commit()
    conn.close()


def create_item(title, description=""):
    conn = get_db()
    now = datetime.utcnow().isoformat() + "Z"
    cur = conn.execute(
        "INSERT INTO items (title, description, created_at, updated_at) VALUES (?, ?, ?, ?)",
        (title, description, now, now)
    )
    item_id = cur.lastrowid
    conn.execute(
        "INSERT INTO receipts (action, entity_id, details, timestamp) VALUES (?, ?, ?, ?)",
        ("create", item_id, json.dumps({"title": title}), now)
    )
    conn.commit()
    conn.close()
    return item_id


def list_items(status=None):
    conn = get_db()
    if status:
        rows = conn.execute("SELECT * FROM items WHERE status = ? ORDER BY id DESC", (status,)).fetchall()
    else:
        rows = conn.execute("SELECT * FROM items ORDER BY id DESC").fetchall()
    conn.close()
    return [dict(r) for r in rows]


def complete_item(item_id):
    conn = get_db()
    now = datetime.utcnow().isoformat() + "Z"
    conn.execute("UPDATE items SET status = 'done', updated_at = ? WHERE id = ?", (now, item_id))
    conn.execute(
        "INSERT INTO receipts (action, entity_id, details, timestamp) VALUES (?, ?, ?, ?)",
        ("complete", item_id, "{}", now)
    )
    conn.commit()
    conn.close()


def get_receipts(limit=20):
    conn = get_db()
    rows = conn.execute("SELECT * FROM receipts ORDER BY id DESC LIMIT ?", (limit,)).fetchall()
    conn.close()
    return [dict(r) for r in rows]
