"""VaultOps — Tests. Auto-generated by HyperFlow Autonomous Loop."""

import sys
import tempfile
from pathlib import Path
import pytest

sys.path.insert(0, str(Path(__file__).parent))


@pytest.fixture(autouse=True)
def temp_db(monkeypatch):
    with tempfile.TemporaryDirectory() as td:
        monkeypatch.setattr("db.DB_PATH", Path(td) / "test.db")
        from db import init_db
        init_db()
        yield


def test_create():
    from db import create_item, list_items
    tid = create_item("Test")
    assert tid > 0
    assert len(list_items()) == 1


def test_complete():
    from db import create_item, complete_item, list_items
    tid = create_item("Done me")
    complete_item(tid)
    assert list_items("done")[0]["status"] == "done"


def test_receipts():
    from db import create_item, get_receipts
    create_item("Receipt test")
    assert len(get_receipts()) >= 1
